package errors

// AttachTo выполняет функцию f и комбинирует ошибку от неё с target.
func AttachTo(target *error, f func() error) {
	// Реализуй меня.
}
